version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - juno
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
