version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 30
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
